language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
# command to install dependencies
install:
  - pip install -r requirements/local.txt
# command to run tests
before_script: cd src/
script:
  - python -m unittest test/index_test.py
  