version: '3'

services:
  web:
    container_name: nginx
    env_file: .env
    environment:
      - EX_PORT_NGINX=$EX_PORT_NGINX
      - PORT_NGINX=$PORT_NGINX
    image: nginx:alpine
    restart: always
    ports:
      - "$EX_PORT_NGINX:$PORT_NGINX"
    volumes:
      - ./log:/log
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime:ro
    links:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
  app:
    container_name: flask-app
    env_file: .env
    build: 
      context: .
      dockerfile: ./compose/production/Dockerfile
    restart: always
    command: gunicorn wsgi:app -b 0.0.0.0:8011 --log-level=info
    volumes:
      - ./src:/home/app/web/
      - ./logs:/home/app/web/logs
      - /etc/localtime:/etc/localtime:ro
    links:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
  worker:
    container_name: worker1
    env_file: .env
    build: 
      context: .
      dockerfile: ./compose/production/Dockerfile
    restart: always
    command: celery -A app.task worker --loglevel=info -f logs/beat.log
    volumes:
      - ./src:/home/app/web/
      - ./logs:/home/app/web/logs
      - /etc/localtime:/etc/localtime:ro
    links:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"  
  beat:
    container_name: beat1
    env_file: .env
    build: 
      context: .
      dockerfile: ./compose/production/Dockerfile
    restart: always
    command: celery -A app.task beat --loglevel=info
    volumes:
      - ./src:/home/app/web/
      - ./logs:/home/app/web/logs
      - /etc/localtime:/etc/localtime:ro
    links:
      - redis
  flower:
    container_name: flower
    env_file: .env
    environment:
      - FLOWER_EXPOSE=$FLOWER_EXPOSE
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
    build: 
      context: .
      dockerfile: ./compose/production/Dockerfile
    volumes:
      - ./src:/home/app/web/
    entrypoint: flower
    command:  -A app.task --port=5555 --broker=${CELERY_BROKER_URL}
    ports:
     - "$FLOWER_EXPOSE:5555"
    depends_on:
      - redis
  redis:
    container_name: redis_ox
    image: redis
    volumes:
      - ./data/redis:/data
    restart: always